spring:
  elasticsearch:
    rest:
      uris: http://192.168.0.52:9200
  datasource:
    url: jdbc:mysql://localhost:3306/reghao_im_rdb?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: dev
    password: Dev@123456
dubbo:
  registry:
    address: zookeeper://localhost:2181